In [23]:
import numpy as np
import control

In [40]:
np.random.seed(1123)
A = np.asmatrix(np.random.random([3,3]))
print(A)
#b = np.random.random([3,1])
b = np.matrix('[0;0;1]')

[[0.3144082  0.924563   0.41890814]
 [0.05678322 0.63841102 0.0937656 ]
 [0.51524553 0.64574343 0.35365654]]


In [41]:
# Eigen values
Lambda, _ = np.linalg.eig(A)
print(Lambda)

[-0.11784065  1.07343823  0.35087818]


In [42]:
V = np.vander(Lambda)
print(V)

[[ 0.01388642 -0.11784065  1.        ]
 [ 1.15226963  1.07343823  1.        ]
 [ 0.1231155   0.35087818  1.        ]]


In [43]:
MC = V @ A @ np.linalg.inv(V)
print(MC)

[[-0.33440683  0.42121658  0.26161452]
 [-3.79997198  0.39649529  4.34047993]
 [-1.18562836  0.37937198  1.2443873 ]]


In [46]:
M = np.asmatrix(control.ctrb(A, b))

print(np.round(M.I @ A @ M,5))

[[ 0.       0.      -0.04438]
 [ 1.      -0.      -0.2088 ]
 [ 0.       1.       1.30648]]
