In [1]:
import numpy as np

In [9]:
np.random.seed(1123)
A = np.random.random([3,3])
print(A)

[[0.3144082  0.924563   0.41890814]
 [0.05678322 0.63841102 0.0937656 ]
 [0.51524553 0.64574343 0.35365654]]


In [10]:
# Eigen values
Lambda, _ = np.linalg.eig(A)
print(Lambda)

[-0.11784065  1.07343823  0.35087818]


In [ ]:
# 